name: 推送打包Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # 增加构建超时时间（AAPT2处理大资源文件可能需要更长时间）
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: 修复并优化图片资源
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick webp pngquant optipng
        
        # 修复损坏的PNG并转换为WebP
        find app/src/main/res -name "*.png" | while read file; do
          if ! identify "$file" &>/dev/null; then
            echo "⚠️ 修复损坏的PNG: $file"
            convert "$file" -define png:format=png32 "${file}.fixed" && mv "${file}.fixed" "$file"
          fi
          
          # 转换为WebP（可选）
          cwebp -q 80 "$file" -o "${file%.*}.webp" && rm "$file"
        done
    
    - name: 授予gradlew执行权限
      run: chmod +x gradlew
      
    # 增加构建内存并启用详细日志
    - name: 使用Gradle构建
      run: |
        ./gradlew clean assembleRelease \
          --stacktrace \
          --info \
          -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=1g"
      env:
        # 增加AAPT2可用内存
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
        
    - name: 构建APK
      run: ./gradlew clean assembleRelease --stacktrace
      env:
        JAVA_OPTS: "-Xmx4g"
