name: 推送Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install pngquant (优化 PNG)
        run: sudo apt-get install -y pngquant
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build --stacktrace
        env:
          JAVA_OPTS: "-Xmx4g"  # 增加 JVM 内存
