name: 推送打包Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # 增加构建超时时间（AAPT2处理大资源文件可能需要更长时间）
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    # 关键步骤：安装图片优化工具并处理PNG文件
    - name: 优化PNG资源文件
      run: |
        sudo apt-get update
        sudo apt-get install -y pngquant optipng
        echo "正在优化res目录下的PNG文件..."
        find app/src/main/res -name "*.png" -print0 | while IFS= read -r -d '' file; do
          echo "优化: $file"
          pngquant --force --quality 60-85 --skip-if-larger --output "$file.tmp" "$file"
          mv "$file.tmp" "$file"
          optipng -quiet -o2 "$file"
        done
    
    - name: 授予gradlew执行权限
      run: chmod +x gradlew
    
    # 增加构建内存并启用详细日志
    - name: 使用Gradle构建
      run: |
        ./gradlew clean assembleRelease \
          --stacktrace \
          --info \
          -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=1g"
      env:
        # 增加AAPT2可用内存
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
